#!/bin/bash
set -exu

source $(dirname $0)/version

cd $(dirname $0)/../

# install K3d
K3D_VERSION=latest ./.github/workflows/scripts/install-k3d.sh

if [ -z "${ARCH:-}" ] ; then
    ARCH=$(go env GOHOSTARCH)
fi

# clear the default cluster information
registry_len=$(k3d registry list -o json | jq '. | length ')
if [ "${registry_len}" -gt 0 ]; then
        k3d registry delete k3d-gha
fi
cluster_len=$(k3d cluster list -o json | jq '. | length ')
if [ "${cluster_len}" -gt 0 ]; then
        k3d cluster delete webhook
fi

# setup cluster
CLUSTER_NAME=webhook K3S_VERSION=v1.28.11-k3s1 ARCH=${ARCH} ./.github/workflows/scripts/setup-cluster.sh

# import image
k3d image import dist/rancher-webhook-image.tar -c webhook

# start rancher
VERSION=2.8 RANCHER_IMAGE_TAG=v2.8-head ./.github/workflows/scripts/start-rancher.sh

CI=${CI} IMAGE_REPO=cnrancher/webhook IMAGE_TAG=${TAG} CLUSTER_NAME=webhook ARCH=${ARCH} ./.github/workflows/scripts/integration-test-ci
