#!/bin/bash
set -exu

cd $(dirname $0)/../

#source ./.github/workflows/scripts/try.sh

K3D_VERSION=latest ./.github/workflows/scripts/install-k3d.sh

if [ -z "${ARCH:-}" ] ; then
    ARCH=$(go env GOHOSTARCH)
fi

CLUSTER_NAME=webhook K3S_VERSION=v1.28.11-k3s2 ARCH=${ARCH} ./.github/workflows/scripts/setup-cluster.sh

# import image
k3d image import dist/rancher-webhook-image.tar -c webhook

# start rancher
VERSION=2.9 RANCHER_IMAGE_TAG=v2.9-head ./.github/workflows/scripts/start-rancher.sh

IMAGE_REPO=cnrancher/webhook IMAGE_TAG=$(cat dist/image_tag) CLUSTER_NAME=webhook ARCH=${ARCH} ./.github/workflows/scripts/integration-test-ci
