# Add a comment to force a change.

name: Webhook CI

on:
  push:
    branches:
      - release/v*-todo
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
  pull_request:
    paths-ignore:
    - '.gitignore'
    - 'CODEOWNERS'
    - 'LICENSE'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: CI
    strategy:
      fail-fast: false
      matrix:
        archBox:
        - { arch: amd64, vmArch: x64 }
#        - { arch: arm64, vmArch: arm64 }
    runs-on: org-cnrancher-runner-k8s
    container: ubuntu:22.04
    steps:
      - name : Checkout repository
        # https://github.com/actions/checkout/releases/tag/v4.1.1
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Go
        # https://github.com/actions/setup-go/releases/tag/v5.0.0
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: 'go.mod'

      - name: install K3d
        run: ./.github/workflows/scripts/install-k3d.sh
        env:
          K3D_VERSION: latest

      - name: ci
        run: make ci

      - name: setup cluster
        run: ./.github/workflows/scripts/setup-cluster.sh
        env:
          CLUSTER_NAME: webhook
          K3S_VERSION: v1.28.9-k3s1
          ARCH: "${{ matrix.archBox.arch }}"

      - name: import image
        run: k3d image import dist/rancher-webhook-image.tar -c webhook

      - name: start rancher
        run: ./.github/workflows/scripts/start-rancher.sh
        env:
          RANCHER_IMAGE_TAG: "head"

      - name: get vars
        run: cat dist/image_tag >> $GITHUB_ENV

      - name: Run integration tests
        run: ./.github/workflows/scripts/integration-test-ci
        env:
          ARCH: "${{ matrix.archBox.arch }}"
          CLUSTER_NAME: webhook
          IMAGE_REPO: cnrancher/webhook
          IMAGE_TAG: "${{ env.IMAGE_TAG }}"
