image:
  repository: cnrancher/rancher-webhook
  tag: latest
  imagePullPolicy: IfNotPresent

global:
  cattle:
    systemDefaultRegistry: ""
  hostNetwork: false

capi:
  enabled: false

mcm:
  enabled: true

# tolerations for the webhook deployment. See https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/ for more info
tolerations: []
nodeSelector: {}

## PriorityClassName assigned to deployment.
priorityClassName: ""
